<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Images\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\Iranian Sans.ttf" />
    <None Remove="Fonts\Vazir-Bold.ttf" />
    <None Remove="Fonts\Vazir-Medium.ttf" />
    <None Remove="Images\gold.png" />
    <None Remove="Images\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\Vazir-Bold.ttf" />
    <Resource Include="Fonts\Vazir-Medium.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="PersianDateTimeWPFTools" Version="1.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\Iranian Sans.ttf" />
    <Resource Include="Images\gold.png" />
    <Resource Include="Images\logo.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>

</Project>
